"""Build MuJobs' bilingual static website. Run python3 scripts/build-site.py."""
from pathlib import Path
from html import escape as esc
from urllib.parse import quote
import json,sys,math,xml.etree.ElementTree as ET
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'content'))
from editorial import MARKETS,ARTICLE_SECTIONS,CASE_DETAIL,P
cases=json.loads((ROOT/'content/cases.json').read_text()); articles=json.loads((ROOT/'content/articles.json').read_text())
BASE='https://www.mujobs.de'; LANG='en'; built=[]
def t(pair):return pair[0 if LANG=='en' else 1]
def e(x):return esc(str(x),quote=True)
def tx(en,de):return e(t(P(en,de)))
def url(file='index.html',lang=None):return ('/de/' if (lang or LANG)=='de' else '/')+('' if file=='index.html' else file)
def a(file,label,cls=''):return f'<a class="{cls}" href="{url(file)}">{e(label)}</a>'
def p(s):return '<p>'+e(s)+'</p>'
def bullets(items):return '<ul class="check-list">'+''.join('<li>'+e(x)+'</li>' for x in items)+'</ul>'
def brand():return a('index.html','mujobs','wordmark')+'<span class="brand-dot" aria-hidden="true">.</span>'
def nav():return a('work.html',t(P('Our work','Unsere Projekte')))+a('index.html#markets',t(P('Industries & roles','Branchen & Rollen')))+a('insights.html',t(P('Insights','Einblicke')))+a('index.html#method',t(P('Our approach','Unser Ansatz')))
def cta():return f'<section class="closing wrap" id="contact"><div><span class="eyebrow">{tx("LET’S DEFINE YOUR SEARCH","LASSEN SIE UNS IHRE SUCHE KLÄREN")}</span><h2>{tx("A difficult role. A clearer way forward.","Eine anspruchsvolle Rolle. Ein klarer nächster Schritt.")}</h2><p>{tx("Tell us what the person needs to achieve. We’ll start with the business problem, then shape the search around it.","Erzählen Sie uns, was die neue Person erreichen soll. Wir beginnen mit Ihrer Aufgabe und richten die Suche darauf aus.")}</p></div><a class="button light" href="mailto:mujtaba@mujobs.de">{tx("Discuss a role","Eine Position besprechen")}</a></section>'
def footer():
    body='<footer class="site-footer"><div class="wrap"><div class="footer-grid"><div class="footer-intro"><div class="brand">'+brand()+'</div><h2>'+tx('Good people. Meaningful progress.','Gute Menschen. Gemeinsam weiter.')+'</h2><p>'+tx('Independent recruitment and active sourcing for specialist and leadership roles in Germany and Switzerland.','Unabhängige Personalberatung und Active Sourcing für Fach- und Führungspositionen in Deutschland und der Schweiz.')+'</p><a class="text-link" href="mailto:mujtaba@mujobs.de">mujtaba@mujobs.de</a></div><nav aria-label="'+tx('Explore MuJobs','MuJobs entdecken')+'"><span class="eyebrow">'+tx('EXPLORE','ENTDECKEN')+'</span>'+nav()+'</nav><nav aria-label="'+tx('Recruitment specialisms','Recruiting-Fachbereiche')+'"><span class="eyebrow">'+tx('INDUSTRIES & ROLES','BRANCHEN & ROLLEN')+'</span>'+''.join(a(m['slug']+'.html',t(m['name'])) for m in MARKETS)+'</nav></div><div class="footer-base"><span>© 2026 MuJobs</span><span>'+tx('Based in Berlin · Recruiting across Germany & Switzerland','In Berlin zu Hause · Personalsuche in Deutschland & der Schweiz')+'</span></div></div></footer>'
    return body

def page(file,title,description,body,kind='website',schema=None):
    description=description.strip()
    if len(description)>175:description=description[:172].rsplit(' ',1)[0]+'…'
    canonical=BASE+url(file)
    switch='<div class="language-switch" role="group" aria-label="'+tx('Choose language','Sprache wählen')+'">'+''.join(f'<a href="{url(file,l)}" lang="{l}" hreflang="{l}" aria-label="{label}"'+(' aria-current="page"' if l==LANG else '')+'>'+l.upper()+'</a>' for l,label in [('en','English'),('de','Deutsch')])+'</div>'
    alternates=''.join(f'<link rel="alternate" hreflang="{l}" href="{BASE+url(file,"en" if l=="x-default" else l)}">' for l in ['en','de','x-default'])
    data=schema or {'@context':'https://schema.org','@type':'WebPage','name':title,'description':description,'url':canonical,'inLanguage':LANG}
    html=f'''<!doctype html><html lang="{LANG}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)}</title><meta name="description" content="{e(description)}"><link rel="canonical" href="{canonical}">{alternates}<meta property="og:type" content="{kind}"><meta property="og:title" content="{e(title)}"><meta property="og:description" content="{e(description)}"><meta property="og:url" content="{canonical}"><meta property="og:site_name" content="MuJobs"><meta property="og:locale" content="{'de_DE' if LANG=='de' else 'en_GB'}"><meta property="og:image" content="{BASE}/preview-assets/architecture.jpg"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="/editorial.css"><script src="/site.js" defer></script><script type="application/ld+json">{json.dumps(data,ensure_ascii=False).replace('<','\\u003c')}</script></head><body><a class="skip" href="#main">{tx('Skip to content','Zum Inhalt springen')}</a><header class="header"><div class="wrap nav-row"><div class="brand">{brand()}</div><nav class="desktop" aria-label="{tx('Main navigation','Hauptnavigation')}">{nav()}</nav>{switch}<a class="contact-link" href="mailto:mujtaba@mujobs.de">{tx('Let’s talk','Kontakt')}</a><details class="menu"><summary>{tx('Menu','Menü')}</summary><nav aria-label="{tx('Mobile navigation','Mobile Navigation')}">{nav()}<a href="mailto:mujtaba@mujobs.de">{tx('Contact','Kontakt')}</a></nav></details></div></header><main id="main">{body}</main>{footer()}</body></html>'''
    path=ROOT/('de' if LANG=='de' else '')/file;path.parent.mkdir(parents=True,exist_ok=True);path.write_text(html+'\n');built.append((file,LANG))
def hero(kicker,title,intro,back=None):return '<section class="wrap page-hero">'+(f'<div class="breadcrumb">{a(back[0],back[1])}<span>/</span><span>{e(kicker)}</span></div>' if back else f'<span class="eyebrow">{e(kicker)}</span>')+f'<h1>{e(title)}</h1><p class="lead">{e(intro)}</p></section>'
def sector_for(c):return CASE_DETAIL[c['file'][11:-5]][0]
def sector(slug):return next(m for m in MARKETS if m['slug']==slug)
def card(c):
    d=c['locales'][LANG]; cat=sector_for(c);slug=c['file'][11:-5]
    status=t(P('Completed hire','Erfolgreiche Besetzung'))
    return f'<article class="work-card" data-sector="{cat}"><div class="card-meta"><span>{e(t(sector(cat)["name"]))}</span><span>{e(status)}</span></div><h3>{a(c["file"],d["title"])}</h3><p>{e(d["intro"])}</p><div class="card-bottom"><span>{e(d["metrics"][0][0])} {e(d["metrics"][0][1])}</span>{a(c["file"],t(P('Explore the search','Suche ansehen')),'text-link')}</div></article>'
def work_cards(tags=None):
    selected=cases if tags is None else [next(c for c in cases if c['file']=='case-study-'+tag+'.html') for tag in tags]
    return '<div class="work-grid">'+''.join(card(c) for c in selected)+'</div>'
def related_article(slug):
    ar=next(x for x in articles if x['slug']==slug);d=ar['locales'][LANG]
    return f'<aside class="related"><span class="eyebrow">{tx("READ NEXT","WEITERLESEN")}</span><h3>{a("insight-"+slug+".html",d["title"])}</h3><p>{e(d["intro"])}</p></aside>'
def insight_card(ar,i):
    d=ar['locales'][LANG]
    return f'<article class="insight-card"><span class="article-number">{i+1:02d}</span><div><span class="eyebrow">{e(t(P(["PASSIVE TALENT","ACTIVE SOURCING","REAL ESTATE","TALENT PIPELINES","CANDIDATE ASSESSMENT","GERMANY & SWITZERLAND"],["PASSIVE KANDIDATEN","ACTIVE SOURCING","IMMOBILIEN","KANDIDATENPIPELINES","EIGNUNGSPRÜFUNG","DEUTSCHLAND & SCHWEIZ"]))[i])}</span><h2>{a("insight-"+ar["slug"]+".html",d["title"])}</h2><p>{e(d["intro"])}</p>{a("insight-"+ar["slug"]+".html",t(P("Read article","Artikel lesen")),"text-link")}</div></article>'
def comparison():
    body='<section class="comparison wrap section" id="search-comparison"><div class="section-heading"><span class="eyebrow">'+tx('INBOUND VS. ACTIVE SOURCING','INBOUND VS. ACTIVE SOURCING')+'</span><h2>'+tx('Less screening. More relevant conversations.','Weniger Sichtungsaufwand. Passendere Gespräche.')+'</h2><p>'+tx('Two recruitment projects. Two different routes to a successful hire.','Zwei Recruiting-Projekte. Zwei unterschiedliche Wege zur erfolgreichen Besetzung.')+'</p></div><div class="comparison-grid recruitment-funnels">'
    examples=[('traditional',P('INBOUND APPLICATIONS','EINGEHENDE BEWERBUNGEN'),P('A large funnel. Months of work.','Viele Bewerbungen. Monate an Arbeit.'),P('Frontend recruitment','Frontend-Recruiting'),[('1,071',P('applications received','eingegangene Bewerbungen')),('90',P('first conversations','Erstgespräche')),('13',P('technical interviews','technische Interviews')),('5',P('passed assessment','fachlich geeignet')),('1',P('successful hire','erfolgreiche Besetzung'))],P('Months of recruitment work','Monatelanger Recruiting-Aufwand'),P(['High application volume means extensive CV screening.','Repeated screening and interview rounds take internal team time.','Reach depends on who is actively applying.'],['Viele Bewerbungen bedeuten umfangreiche Lebenslaufsichtung.','Wiederholte Auswahl- und Interviewrunden binden interne Kapazitäten.','Die Reichweite hängt davon ab, wer sich aktiv bewirbt.'])),('focused',P('THE MUJOBS METHOD','DIE MUJOBS-METHODE'),P('A focused search. A faster decision.','Gezielte Suche. Schnellere Entscheidung.'),P('Leiter Vermarktung · Switzerland','Leiter Vermarktung · Schweiz'),[('30',P('relevant profiles sourced','passende Profile recherchiert')),('20',P('positive responses','positive Rückmeldungen')),('5',P('first calls','Erstgespräche')),('1',P('successful hire','erfolgreiche Besetzung'))],P('1.5 weeks to hire','1,5 Wochen bis zur Besetzung'),P(['Targeted research around the role and the business.','Personal outreach reaches suitable passive candidates.','Motivation and experience checked before the shortlist.','A smaller, relevant pool reduces the client’s screening workload.'],['Gezielte Recherche nach Rolle und Unternehmensbedarf.','Persönliche Direktansprache erreicht passende passive Kandidaten.','Motivation und Erfahrung werden vor der Vorauswahl geprüft.','Ein kleinerer, relevanter Kandidatenkreis reduziert Ihren Sichtungsaufwand.']))]
    for cls,kicker,head,context,metrics,timing,points in examples:
        body+='<article class="comparison-card '+cls+'"><span class="eyebrow">'+e(t(kicker))+'</span><h3>'+e(t(head))+'</h3><p class="funnel-context">'+e(t(context))+'</p><ol class="pipeline">'
        for i,(number,label) in enumerate(metrics):
            if LANG=='de':number=number.replace(',','.')
            body+='<li style="--stage:'+str(i)+'"><strong>'+number+'</strong><span>'+e(t(label))+'</span></li>'
        body+='</ol><p class="time-result">'+e(t(timing))+'</p>'+bullets(t(points))+'</article>'
    body+='</div><p class="comparison-note">'+tx('Figures from two separate projects with different roles and requirements. Results illustrate these searches; timing varies by assignment.','Zahlen aus zwei eigenständigen Projekten mit unterschiedlichen Rollen und Anforderungen. Die Ergebnisse beziehen sich auf diese Suchen; die Dauer variiert je Auftrag.')+'</p></section>'
    return body

def home():
    title=t(P('Recruitment & Active Sourcing in Germany and Switzerland | MuJobs','Personalberatung & Active Sourcing Deutschland, Schweiz | MuJobs'))
    intro=t(P('Focused recruitment for real estate, technology, marketing and commercial teams. We find relevant people, explain why they fit and move the search forward.','Gezielte Personalsuche für Immobilien, Technologie, Marketing und Vertrieb. Wir finden passende Menschen, begründen unsere Auswahl und bringen die Suche voran.'))
    body=f'<section class="wrap home-hero"><div><span class="eyebrow">{tx("INDEPENDENT SEARCH · GERMANY & SWITZERLAND","UNABHÄNGIGE PERSONALSUCHE · DEUTSCHLAND & SCHWEIZ")}</span><h1>{tx("The right people for", "Die richtigen Menschen für")}<br><em>{tx("your next chapter.","Ihren nächsten Schritt.")}</em></h1><p class="lead">{e(intro)}</p><div class="actions"><a class="button" href="mailto:mujtaba@mujobs.de">{tx("Discuss your next hire","Ihre nächste Besetzung besprechen")}</a>{a("work.html",t(P("Explore our work","Unsere Projekte entdecken")),"text-link")}</div></div><figure class="hero-image"><img src="/preview-assets/team.jpg" width="1279" height="1919" alt="{tx("People working together around a shared project","Menschen arbeiten gemeinsam an einem Projekt")}" fetchpriority="high"><div class="image-inset"><img src="/preview-assets/architecture.jpg" width="1400" height="933" alt="{tx("Commercial buildings representing the real estate sector","Gewerbeimmobilien als Motiv für die Immobilienbranche")}"></div><figcaption>{tx("PEOPLE BEHIND THE PROJECT.","DIE MENSCHEN HINTER DEM PROJEKT.")}</figcaption></figure></section>'
    body+='<section id="why" class="wrap service-intro"><div class="section-heading"><span class="eyebrow">'+tx('WHAT WE DO','WAS WIR FÜR SIE TUN')+'</span><h2>'+tx('We find the people your business needs.','Wir finden die Menschen, die Ihr Unternehmen braucht.')+'</h2><p>'+tx('From the first search to a qualified shortlist, MuJobs takes on the research, candidate outreach and coordination that keep your hiring moving.','Von der ersten Recherche bis zur qualifizierten Vorauswahl übernimmt MuJobs die Suche, Kandidatenansprache und Koordination für Ihre nächste Besetzung.')+'</p></div><div class="service-deliverables">'
    for head,copy in [(P('Find the right profiles','Passende Profile finden'),P('A targeted market map built around your position, sector and location.','Eine gezielte Marktübersicht für Ihre Position, Branche und Region.')),(P('Start relevant conversations','Relevante Gespräche führen'),P('Personal outreach, follow-ups and initial checks on experience and motivation.','Persönliche Ansprache, Nachfassen und erste Prüfung von Erfahrung und Motivation.')),(P('Bring the shortlist together','Die Vorauswahl zusammenführen'),P('Clear candidate summaries and interview coordination, ready for your decision.','Aussagekräftige Kandidatenprofile und abgestimmte Interviews als Grundlage Ihrer Entscheidung.'))]:
        body+='<article><h3>'+e(t(head))+'</h3><p>'+e(t(copy))+'</p></article>'
    body+='</div></section>'
    body+=f'<section id="markets" class="wrap section"><div class="section-heading"><span class="eyebrow">{tx("INDUSTRIES & SPECIALISMS","BRANCHEN & FACHBEREICHE")}</span><h2>{tx("Recruitment for the markets you work in.","Personalberatung für Ihre Branche.")}</h2><p>{tx("Real estate, technology, marketing, sales and more. Find your sector, see the positions we recruit for and explore how we approach the search.","Immobilien, IT, Marketing, Vertrieb und mehr. Finden Sie Ihren Fachbereich, entdecken Sie passende Positionen und erfahren Sie, wie wir Ihre Suche angehen.")}</p></div><div class="market-grid">'
    for i,m in enumerate(MARKETS):body+=f'<a class="market-card" href="{url(m["slug"]+".html")}"><span class="eyebrow">0{i+1}</span><h3>{e(t(m["name"]))}</h3><p>{e(t(m["kicker"]))}</p><span class="text-link">{tx("Explore roles & sector","Branche & Rollen entdecken")}</span></a>'
    body+='</div></section>'
    body+=comparison()
    body+='<section id="method" class="method-section"><div class="wrap section"><div class="section-heading"><span class="eyebrow">'+tx('THE MUJOBS METHOD','DIE MUJOBS-METHODE')+'</span><h2>'+tx('A clear path to your next hire.','Ein klarer Weg zu Ihrer nächsten Besetzung.')+'</h2><p>'+tx('You stay close to the decision. We keep the search moving, with clear steps and a useful result at every stage.','Sie bleiben nah an der Entscheidung. Wir bringen die Suche voran – mit klaren Schritten und einem greifbaren Ergebnis in jeder Phase.')+'</p></div><ol class="method-cards">'
    stages=[(P('Understand','Verstehen'),P('Define the role, responsibilities and must-have experience together.','Rolle, Aufgaben und unverzichtbare Erfahrung gemeinsam klären.'),P('Your agreed search brief','Ihr abgestimmtes Suchprofil')),(P('Find & engage','Finden & ansprechen'),P('Research the market and personally approach relevant candidates.','Den Markt recherchieren und passende Kandidaten persönlich ansprechen.'),P('A focused candidate pipeline','Eine gezielte Kandidatenpipeline')),(P('Qualify','Qualifizieren'),P('Explore experience, motivation and availability before introducing candidates.','Erfahrung, Motivation und Verfügbarkeit vor der Vorstellung prüfen.'),P('A reasoned shortlist','Eine begründete Vorauswahl')),(P('Move to a decision','Zur Entscheidung kommen'),P('Coordinate interviews, collect feedback and support the final steps.','Interviews koordinieren, Feedback einholen und die letzten Schritte begleiten.'),P('A coordinated hiring process','Ein abgestimmter Besetzungsprozess'))]
    for head,copy,result in stages:
        body+='<li><h3>'+e(t(head))+'</h3><p>'+e(t(copy))+'</p><div class="method-result"><span>'+tx('YOU RECEIVE','IHR ERGEBNIS')+'</span><strong>'+e(t(result))+'</strong></div></li>'
    body+='</ol></div></section>'
    body+=f'<section id="work" class="tinted"><div class="wrap section"><div class="section-heading"><span class="eyebrow">{tx("SELECTED WORK","AUSGEWÄHLTE PROJEKTE")}</span><h2>{tx("Selected work. Successful hires.","Ausgewählte Projekte. Erfolgreiche Besetzungen.")}</h2><p>{tx("The business challenge, the search decisions and what happened next. Explore individual projects across specialist and commercial roles.","Die unternehmerische Aufgabe, die Entscheidungen in der Suche und das Ergebnis. Entdecken Sie Projekte für Fach- und kaufmännische Positionen.")}</p></div>'+work_cards(['leiter-vermarktung','project-developer','creative-director'])+f'<div class="section-footer"><p>{tx("Each project has its own brief and context.","Jedes Projekt hat sein eigenes Profil und seinen Kontext.")}</p>{a("work.html",t(P("Browse all work","Alle Projekte ansehen")),"button outline")}</div></div></section>'
    body+=f'<section class="wrap section"><div class="section-heading"><span class="eyebrow">{tx("INSIGHTS","EINBLICKE")}</span><h2>{tx("Practical ideas for hard-to-fill roles.","Impulse für anspruchsvolle Besetzungen.")}</h2></div><div class="insight-list">'+''.join(insight_card(x,i) for i,x in enumerate(articles[:2]))+'</div><div class="section-footer">'+a('insights.html',t(P('Explore all insights','Alle Einblicke ansehen')),'button outline')+'</div></section>'+cta()
    page('index.html',title,intro,body)
def works():
    body=hero(t(P('OUR WORK','UNSERE PROJEKTE')),t(P('Every role has a story.','Hinter jeder Rolle steht eine Aufgabe.')),t(P('Completed recruitment projects across real estate, technology, marketing, sales and pharma. Explore the role, the market, our direct-search approach and the outcome.','Erfolgreiche Besetzungen in Immobilien, IT, Marketing, Vertrieb und Pharma. Entdecken Sie Anforderungsprofil, Markt, Direktansprache und Ergebnis jedes Suchprojekts.')))
    body+='<section class="wrap section compact"><div class="filters" hidden aria-label="'+tx('Filter work by sector','Projekte nach Branche filtern')+'"><button type="button" data-filter="all" aria-pressed="true">'+tx('All work','Alle Projekte')+'</button>'
    for m in MARKETS:
        if any(sector_for(c)==m['slug'] for c in cases):body+=f'<button type="button" data-filter="{m["slug"]}" aria-pressed="false">{e(t(m["name"]))}</button>'
    body+='</div><p class="result-count" aria-live="polite"></p>'+work_cards()+'</section>'+cta()
    page('work.html',t(P('Recruitment Case Studies & Search Projects | MuJobs','Recruiting-Fallstudien & Suchprojekte | MuJobs')),t(P('Explore MuJobs recruitment projects in real estate, sales, technology, marketing and pharma. Hiring challenges, search approaches and outcomes.','MuJobs-Suchprojekte für Immobilien, Vertrieb, IT, Marketing und Pharma: Herausforderungen, Suchmethoden und Ergebnisse im Überblick.')),body)
def case_pages():
    for c in cases:
        d=c['locales'][LANG];slug=c['file'][11:-5];cat,heading,context,checks=CASE_DETAIL[slug];m=sector(cat)
        body=hero(d['label'],t(heading),d['intro'],('work.html',t(P('All work','Alle Projekte'))))
        body+='<section class="wrap case-summary"><span class="pill">'+e(d['signal'])+'</span><div class="metrics">'+''.join(f'<div><strong>{e(v)}</strong><span>{e(label)}</span></div>' for v,label in d['metrics'])+'</div><p class="caption">'+tx('Project-specific figures from the existing case record; not a forecast for another search.','Projektspezifische Angaben aus dem bestehenden Fallbericht; keine Prognose für andere Suchen.')+'</p></section>'
        body+='<div class="wrap reading-layout"><aside class="contents"><span class="eyebrow">'+tx('IN THIS SEARCH','IN DIESER SUCHE')+'</span>'
        heads=[P('The hiring challenge','Die Besetzungsaufgabe'),P('The search approach','Der Suchansatz'),P('The outcome','Das Ergebnis'),P('Understanding the role','Die Rolle verstehen'),P('Planning a similar search','Eine ähnliche Suche planen')]
        body+=''.join(f'<a href="#section-{i}">{i+1:02d} · {e(t(h))}</a>' for i,h in enumerate(heads))+'</aside><article class="reading">'
        for i,paras in enumerate(d['sections']):body+=f'<section id="section-{i}"><span class="eyebrow">0{i+1}</span><h2>{e(t(heads[i]))}</h2>'+''.join(p(x) for x in paras)+'</section>'
        body+='<section id="section-3"><span class="eyebrow">04</span><h2>'+e(t(heads[3]))+'</h2>'+p(t(context))+'<div class="callout"><h3>'+tx('Questions that make the brief more precise','Fragen für ein genaueres Anforderungsprofil')+'</h3>'+bullets(t(checks))+'</div></section>'
        body+='<section id="section-4"><span class="eyebrow">05</span><h2>'+e(t(heads[4]))+'</h2>'+p(t(P('Start with the work the new person will own, the business context and the constraints that cannot change. Separate essential experience from preferences. That gives the market mapping a clear direction and makes it easier to explain why someone belongs on the shortlist.','Beginnen Sie mit der künftigen Verantwortung, dem Unternehmenskontext und unveränderlichen Rahmenbedingungen. Trennen Sie notwendige Erfahrung von Präferenzen. So erhält die Marktanalyse eine klare Richtung und die Vorauswahl eine nachvollziehbare Begründung.')))+p(t(P('A similar title is only a research starting point. In an initial conversation, we would clarify the project or team, the practical conditions and the evidence you need to make a decision. The scope of sourcing, candidate qualification and interview coordination can then be agreed around the actual requirement.','Ein ähnlicher Titel ist nur ein Rechercheausgangspunkt. Im Erstgespräch klären wir Projekt oder Team, praktische Bedingungen und die benötigten Nachweise für Ihre Entscheidung. Darauf aufbauend lässt sich der Umfang von Sourcing, Kandidatenprüfung und Interviewkoordination vereinbaren.')))+a(cat+'.html',t(m['title']),'text-link')+'</section>'+related_article(m['article'])+'</article></div>'
        others=[x for x in m['tags'] if x!=slug][:2]
        if others:body+='<section class="wrap section"><div class="section-heading"><span class="eyebrow">'+tx('RELATED WORK','ÄHNLICHE PROJEKTE')+'</span><h2>'+tx('A different role. A different search.','Andere Rolle. Andere Suche.')+'</h2></div>'+work_cards(others)+'</section>'
        body+=cta();page(c['file'],t(heading)+' | MuJobs',d['intro'],body)
def market_pages():
    for m in MARKETS:
        body=hero(t(m['kicker']),t(m['title']),t(m['intro']),('index.html#markets',t(P('All industries & roles','Alle Branchen & Rollen'))))
        roles_intro='<section id="roles"><span class="eyebrow">'+tx('ROLES AT A GLANCE','POSITIONEN IM ÜBERBLICK')+'</span><h2>'+tx('Positions we recruit for','Positionen, die wir besetzen')+'</h2><div class="role-list">'+''.join('<div>'+e(r)+'</div>' for r in t(m['roles']))+'</div></section>'
        body+='<div class="wrap sector-roles">'+roles_intro+'</div>'
        body+='<div class="wrap reading-layout"><aside class="contents"><span class="eyebrow">'+tx('IN THIS PRACTICE','IN DIESEM FACHBEREICH')+'</span>'+''.join(f'<a href="#{id}">{e(t(label))}</a>' for id,label in [('challenge',P('The hiring challenge','Die Besetzungsaufgabe')),('roles',P('Roles we cover','Unsere Rollenfelder')),('assessment',P('What we assess','Was wir prüfen')),('approach',P('How we search','Wie wir suchen'))])+'</aside><article class="reading">'
        body+='<section id="challenge"><span class="eyebrow">01</span><h2>'+tx('Where the search becomes difficult','Wo die Suche anspruchsvoll wird')+'</h2>'+p(t(m['problem']))+'</section>'

        body+='<section id="assessment"><span class="eyebrow">03</span><h2>'+tx('The evidence behind a relevant shortlist','Die Grundlage einer passenden Vorauswahl')+'</h2>'+p(t(P('Our starting questions connect the role to the work. The final assessment criteria are agreed for your particular brief, rather than applied as a generic checklist.','Unsere Ausgangsfragen verbinden Rolle und Aufgabe. Die endgültigen Bewertungskriterien werden für Ihren konkreten Auftrag vereinbart und nicht als allgemeine Checkliste übernommen.')))+bullets(t(m['evidence']))+'</section>'
        body+='<section id="approach"><span class="eyebrow">04</span><h2>'+tx('Map the market. Make the connection.','Den Markt verstehen. Die Verbindung herstellen.')+'</h2>'+p(t(m['map']))+'<div class="callout"><h3>'+tx('What the search can include','Was die Suche umfassen kann')+'</h3>'+bullets(t(P(['A focused briefing and role-specific market map.','Relevant profile research and personal candidate outreach.','Initial qualification, follow-ups and interview coordination.','A shortlist with clear reasoning and visible open questions.'],['Gezieltes Briefing und rollenspezifische Marktanalyse.','Recherche passender Profile und persönliche Kandidatenansprache.','Erste Eignungsprüfung, Nachfassen und Interviewkoordination.','Eine begründete Vorauswahl mit transparenten offenen Fragen.'])))+'</div></section>'
        body+='<section><h2>'+tx('Start with the brief','Mit dem Profil beginnen')+'</h2>'+p(t(P('Share the responsibility you need to fill, the location, the team structure and what has made the role hard to close. Together, we can distinguish what is essential from what is flexible and agree a search that fits the business.','Teilen Sie uns die gesuchte Verantwortung, Standort, Teamstruktur und bisherige Besetzungshürden mit. Gemeinsam trennen wir unverzichtbare Anforderungen von flexiblen Punkten und vereinbaren eine Suche, die zum Unternehmen passt.')))+'</section>'+related_article(m['article'])+'</article></div>'
        if m['tags']:body+='<section class="wrap section"><div class="section-heading"><span class="eyebrow">'+tx('COMPLETED WORK IN THIS SECTOR','BESETZUNGEN IN DIESEM FACHBEREICH')+'</span><h2>'+tx('From the brief to the right person.','Vom Anforderungsprofil zur Besetzung.')+'</h2></div>'+work_cards(m['tags'])+'</section>'
        body+=cta();page(m['slug']+'.html',t(m['title']).rstrip('.')+' | MuJobs',t(m['intro']),body)
def insight_pages():
    intro=t(P('Practical thinking on active sourcing, real estate recruitment, candidate assessment and hiring in Germany and Switzerland. Choose a topic for the full article.','Praktische Gedanken zu Active Sourcing, Immobilien-Recruiting, Eignungsprüfung und Personalsuche in Deutschland und der Schweiz. Wählen Sie ein Thema für den vollständigen Artikel.'))
    body=hero(t(P('MUJOBS / INSIGHTS','MUJOBS / EINBLICKE')),t(P('A closer look at the search.','Ein genauerer Blick auf die Personalsuche.')),intro)+'<section class="wrap section compact insight-list">'+''.join(insight_card(x,i) for i,x in enumerate(articles))+'</section>'+cta()
    page('insights.html',t(P('Recruitment Insights & Active Sourcing Guides | MuJobs','Recruiting-Einblicke & Active-Sourcing-Praxis | MuJobs')),intro,body)
    for i,ar in enumerate(articles):
        d=ar['locales'][LANG];sections=ARTICLE_SECTIONS[i];file='insight-'+ar['slug']+'.html'
        words=' '.join(d['opening']+[t(s[1]) for s in sections]).split();mins=max(3,math.ceil(len(words)/180))
        body=hero(t(P('FIELD NOTES','PRAXISEINBLICKE')),d['title'],d['intro'],('insights.html',t(P('All insights','Alle Einblicke'))))
        body+='<div class="wrap article-meta"><span>'+tx('By MuJobs','Von MuJobs')+'</span><span>'+str(mins)+' '+tx('min read','Min. Lesezeit')+'</span><span>'+tx('Recruitment practice','Recruiting-Praxis')+'</span></div><div class="wrap reading-layout"><aside class="contents"><span class="eyebrow">'+tx('IN THIS ARTICLE','IN DIESEM ARTIKEL')+'</span>'+''.join(f'<a href="#part-{j}">{e(t(s[0]))}</a>' for j,s in enumerate(sections))+'</aside><article class="reading"><section class="article-opening">'+''.join(p(x) for x in d['opening'])+'</section>'
        for j,(head,para) in enumerate(sections):body+=f'<section id="part-{j}"><span class="eyebrow">0{j+1}</span><h2>{e(t(head))}</h2>'+p(t(para))+'</section>'
        body+='<aside class="takeaway"><span class="eyebrow">'+tx('PUT IT INTO PRACTICE','IN DIE PRAXIS ÜBERTRAGEN')+'</span><h2>'+tx('Bring one live role to the conversation.','Bringen Sie eine konkrete Rolle mit.')+'</h2>'+p(t(P('Take the questions in this article and apply them to the position you are trying to fill. Write down what is known, what is assumed and which conversation would resolve the most important uncertainty. A clearer brief is a practical first step towards a more relevant search.','Übertragen Sie die Fragen dieses Artikels auf Ihre offene Position. Notieren Sie, was bekannt ist, was angenommen wird und welches Gespräch die wichtigste Unsicherheit klären kann. Ein genaueres Profil ist ein praktischer erster Schritt zu einer passenderen Suche.')))+a('work.html',t(P('See how this looks in practice','Beispiele aus der Praxis')),'text-link')+'</aside></article></div>'
        body+='<section class="wrap section"><div class="section-heading"><span class="eyebrow">'+tx('CONTINUE READING','WEITERLESEN')+'</span><h2>'+tx('Another angle on hiring.','Ein weiterer Blick auf Recruiting.')+'</h2></div>'+insight_card(articles[(i+1)%len(articles)],(i+1)%len(articles))+'</section>'+cta()
        schema={'@context':'https://schema.org','@type':'Article','headline':d['title'],'description':d['intro'],'inLanguage':LANG,'author':{'@type':'Organization','name':'MuJobs','url':BASE},'publisher':{'@type':'Organization','name':'MuJobs'},'mainEntityOfPage':BASE+url(file),'wordCount':len(words)}
        page(file,d['title'].rstrip('.')+' | MuJobs',d['intro'],body,'article',schema)
for LANG in ['en','de']:
    home();works();case_pages();market_pages();insight_pages()
ET.register_namespace('','http://www.sitemaps.org/schemas/sitemap/0.9');ET.register_namespace('xhtml','http://www.w3.org/1999/xhtml')
root=ET.Element('{http://www.sitemaps.org/schemas/sitemap/0.9}urlset')
for file,lang in built:
    node=ET.SubElement(root,'url');ET.SubElement(node,'loc').text=BASE+url(file,lang)
    for alt in ['en','de','x-default']:ET.SubElement(node,'{http://www.w3.org/1999/xhtml}link',{'rel':'alternate','hreflang':alt,'href':BASE+url(file,'en' if alt=='x-default' else alt)})
ET.ElementTree(root).write(ROOT/'sitemap.xml',encoding='utf-8',xml_declaration=True)
print('Built',len(built),'pages in English and German')
